In [2]:
import numpy as np
import tensorflow as tf

In [3]:
sess = tf.compat.v1.InteractiveSession()

In [19]:
a = np.zeros([4,5,10])
print(np.max(np.max(a, axis=2), axis=1))


[0. 0. 0. 0.]


In [22]:
a = np.array([[1.,2.],[3.,4.]])
w = np.array([[1.,2.],[3.,4.]])
a = a.reshape([1,2,2,1])
w = w.reshape([2,2,1,1])

a_ = tf.constant(a)
w_ = tf.constant(w)

out_ = tf.nn.conv2d_transpose(a_, w_, output_shape=[1,2,4,1], strides=[1,1,2,1])

In [25]:
out = sess.run(out_)
print(out.reshape([2,4]))
out.shape

[[ 1.  2.  2.  4.]
 [ 6. 10. 10. 16.]]


(1, 2, 4, 1)

In [1]:
import numpy as np
a = np.nan
print(a)

nan


In [4]:
a is np.nan

True